-- RUN THIS SQL IN YOUR SUPABASE SQL EDITOR TO CREATE THE DATABASE SCHEMAS

-- 1. Create institutions table
CREATE TABLE IF NOT EXISTS institutions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  type text NOT NULL, -- 'Public University', 'Private College', 'Public TVET'
  location text NOT NULL,
  legit boolean DEFAULT true
);

-- 2. Create courses table
CREATE TABLE IF NOT EXISTS courses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_id bigint REFERENCES institutions(id) ON DELETE CASCADE,
  name text NOT NULL,
  saqa_id text NOT NULL UNIQUE,
  nqf_level integer NOT NULL, -- 4 to 10
  accredited boolean DEFAULT true
);

-- Enable Row Level Security (RLS) on both tables (optional but recommended)
ALTER TABLE institutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public READ access (anon role)
CREATE POLICY "Allow public read access" ON institutions FOR SELECT TO anon USING (true);
CREATE POLICY "Allow public read access" ON courses FOR SELECT TO anon USING (true);

-- Create policy to allow anon INSERT access for seeding (temporary, or you can run script with service_role key)
CREATE POLICY "Allow anon insert for seeding" ON institutions FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon insert for seeding" ON courses FOR INSERT TO anon WITH CHECK (true);
